services:
  - type: web
    name: my-system-backend
    env: python
    plan: free
    rootDir: .
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CREATE_SUPERUSER
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

