services:
  - type: web
    name: my-system-backend
    env: python
    plan: free
    rootDir: .
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: 'postgresql://neondb_owner:npg_zYVWMZdye5r7@ep-small-art-aigcmjw1-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
      - key: FRONTEND_URL
        value: https://my-system-frontend.onrender.com
      - key: ALLOWED_HOSTS
        value: my-system-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://my-system-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://my-system-frontend.onrender.com
      - key: CREATE_SUPERUSER
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: Admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin@1234




